<a href="https://colab.research.google.com/github/Nirmiteevats/Artificial-Intelligence-and-Machine-Learning/blob/main/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#1
import numpy as np

arr = np.arange(1, 21)

print("Array:", arr)
print("Shape:", arr.shape)
print("Datatype:", arr.dtype)

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Shape: (20,)
Datatype: int64


In [2]:
#2
zeros = np.zeros((3,3))
ones = np.ones((4,4))
identity = np.eye(5)

print("Zeros:\n", zeros)
print("\nOnes:\n", ones)
print("\nIdentity:\n", identity)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Identity:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [3]:
#3
arr1 = np.arange(10,101,10)
arr2 = np.linspace(0,1,5)

print(arr1)
print(arr2)

[ 10  20  30  40  50  60  70  80  90 100]
[0.   0.25 0.5  0.75 1.  ]


In [4]:
#4
arr = np.random.randint(1,51,(3,3))

print(arr)

[[49 30 28]
 [ 9  4  3]
 [28 14 37]]


In [5]:
#5
arr = np.random.randint(1,100,10)

print("Original:", arr)

arr = arr.astype(float)

print("Float:", arr)

Original: [50 58 59 73 58  8 39 96 42 93]
Float: [50. 58. 59. 73. 58.  8. 39. 96. 42. 93.]


In [6]:
#6
a = np.array([10,20,30])
b = np.array([2,4,5])

print("Addition:", a+b)
print("Subtraction:", a-b)
print("Multiplication:", a*b)
print("Division:", a/b)

Addition: [12 24 35]
Subtraction: [ 8 16 25]
Multiplication: [ 20  80 150]
Division: [5. 5. 6.]


In [7]:
#7
arr = np.array([1,4,9,16])

print("Square:", np.square(arr))
print("Square Root:", np.sqrt(arr))
print("Exponential:", np.exp(arr))
print("Log:", np.log(arr))

Square: [  1  16  81 256]
Square Root: [1. 2. 3. 4.]
Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
Log: [0.         1.38629436 2.19722458 2.77258872]


In [8]:
#8
arr = np.array([5,10,15,20,25])

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))

Sum: 75
Mean: 15.0
Max: 25
Min: 5


In [9]:
#9
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print("Matrix Multiplication:\n", A @ B)

print("\nElement-wise Multiplication:\n", A * B)

Matrix Multiplication:
 [[19 22]
 [43 50]]

Element-wise Multiplication:
 [[ 5 12]
 [21 32]]


In [10]:
#10
arr = np.array([2,4,6,8])

print("Add 5:", arr+5)
print("Multiply by 3:", arr*3)

Add 5: [ 7  9 11 13]
Multiply by 3: [ 6 12 18 24]


In [11]:
#11
arr = np.arange(1,13)

print(arr.reshape(3,4))

print()

print(arr.reshape(4,3))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [12]:
#12
arr = np.arange(1,10).reshape(3,3)

print("Flatten:")
print(arr.flatten())

print("Ravel:")
print(arr.ravel())

Flatten:
[1 2 3 4 5 6 7 8 9]
Ravel:
[1 2 3 4 5 6 7 8 9]


In [13]:
#13
arr = np.array([[1,2,3],
                [4,5,6]])

print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


In [14]:
#14
arr = np.arange(1,17)

print(arr.reshape(2,8))

print()

print(arr.reshape(8,2))

print()

print(arr.reshape(4,4))

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [15]:
#15
arr = np.array([1,2,3,4])

arr.resize((2,4))

print(arr)

[[1 2 3 4]
 [0 0 0 0]]


In [16]:
#16
marks = np.array([78,85,90,
                  88,76,95,
                  67,80,72,
                  92,89,94])

marks = marks.reshape(4,3)

print(marks)

[[78 85 90]
 [88 76 95]
 [67 80 72]
 [92 89 94]]


In [17]:
#17
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print("Matrix × 2")

new_matrix = matrix*2

print(new_matrix)

print("\nRow Sum:")

print(np.sum(new_matrix,axis=1))

Matrix × 2
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Row Sum:
[12 30 48]


In [18]:
#18
arr = np.arange(1,17).reshape(4,4)

print("Original Matrix")
print(arr)

print("\nTranspose")
print(arr.T)

print("\nFlatten")
print(arr.flatten())

print("\nReshape into 2x8")
print(arr.reshape(2,8))

print("\nMultiply by 5")
print(arr*5)

print("\nSum of all elements")
print(np.sum(arr))

print("\nMean")
print(np.mean(arr))

print("\nMaximum")
print(np.max(arr))

print("\nMinimum")
print(np.min(arr))

Original Matrix
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Transpose
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]

Flatten
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]

Reshape into 2x8
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]

Multiply by 5
[[ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]
 [65 70 75 80]]

Sum of all elements
136

Mean
8.5

Maximum
16

Minimum
1
